#!/usr/bin/env bash
# Copy the standalone wattbox_local library into the HA integration
# folder so the integration is self-contained when installed via HACS.
# src/wattbox_local/ is the source of truth; the vendored copy under
# custom_components/wattbox/wattbox_local/ is regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="src/wattbox_local"
DST="custom_components/wattbox/wattbox_local"

if [ ! -d "$SRC" ]; then
  echo "missing $SRC" >&2
  exit 1
fi

rm -rf "$DST"
cp -r "$SRC" "$DST"
echo "synced $SRC -> $DST"
