#!/usr/bin/env bash
# Copy the standalone wattbox_local library into the HA integration
# folder so the integration is self-contained when installed via HACS.
# src/wattbox_local/ is the source of truth; the vendored copy under
# custom_components/wattbox/wattbox_local/ is regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="src/wattbox_local"
DST="custom_components/wattbox/wattbox_local"

if [ ! -d "$SRC" ]; then
  echo "missing $SRC" >&2
  exit 1
fi

rm -rf "$DST"
cp -r "$SRC" "$DST"
# Strip caches so check_vendored.sh stays clean.
find "$DST" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
find "$DST" -type f -name '*.pyc' -delete 2>/dev/null || true
echo "synced $SRC -> $DST"
